trigger: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest

variables:
  - group: VuosikelloVariables  # Sisältää WEB_APP_NAME ja muut muuttujat
    
stages:
  - template: './templates/template-terraform-stages.yml'
    parameters: 
      environmentName: 'sandbox'
      serviceconnectionName: 'VuosikelloDevOpsSandbox'
      terraformBasePath: '$(System.DefaultWorkingDirectory)/Terraform'

  # Huomaa: template sisältää jo julkaisuvaiheen, joten käytetään vain sitä
  # Syklinen muuttujaviittaus on korjattu poistamalla toinen julkaisuvaihe
  # Tarvittavien muuttujien pitäisi tulla VuosikelloVariables-ryhmästä